name: build and test

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9', 'pypy-3.6']
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Create a virtual environment
        run: python3 -m venv ./venv && . venv/bin/activate
      - run: pip install -r requirements.txt
      - run: pip install -e .
      - run: python ionhashtest/ion_hash_test_driver.py --help
